# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-24 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20200524_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.DeleteModel(
            name='CompanyName',
        ),
    ]
