# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-24 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20200524_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedetails',
            old_name='short_name',
            new_name='name',
        ),
    ]
