# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-24 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_sharedetails_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedetails',
            name='short_name',
        ),
    ]
