# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-25 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_remove_sharedetails_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedetails',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.DeleteModel(
            name='CompanyDetails',
        ),
    ]
