# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-25 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20200525_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedetails',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='sharedetails',
            old_name='date',
            new_name='date_bought',
        ),
    ]
