# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-26 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_userprofiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfiles',
        ),
    ]
